FROM golang:1.25

WORKDIR /app

# use air for hot reload
RUN go install github.com/air-verse/air@latest

# cache dependencies and copy code
COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["air", "-c", ".air.toml"]
